TEXTS = {
    "en": {
        "welcome_line1": "WELCOME TO 333 BOT",
        "welcome_line2": "STAY UPDATED WITH OUR CHANNEL.",
        "welcome_line3": "TEAM 333",
        "no_access": "You do not have access to use this bot.",
        "choose_option": "Choose an option:",
        "back": "Back",
        "cancel": "Cancel",
        "cancelled": "Action cancelled.",
        "error": "An error occurred. Please try again.",
        "not_authorized": "You are not authorized to perform this action.",

        # Main menu buttons
        "btn_content": "Content",
        "btn_stats": "Statistics",
        "btn_admin": "Admin Panel",
        "btn_settings": "Settings",
        "btn_developer": "Developer",

        # Content menu buttons
        "btn_add_content": "Add Content",
        "btn_my_links": "My Links",
        "btn_view_viewers": "View Viewers",
        "btn_delete_link": "Delete Link",
        "btn_link_settings": "Link Settings",

        # Stats menu buttons
        "btn_all_content": "All Content",
        "btn_popular": "Popular Content",
        "btn_recent_views": "Recent Views",
        "btn_total_views": "Total Views",
        "btn_export": "Export Stats",

        # Admin menu buttons
        "btn_view_admins": "View Admins",
        "btn_add_admin": "Add Admin",
        "btn_remove_admin": "Remove Admin",
        "btn_edit_permissions": "Edit Permissions",
        "btn_admin_stats": "Admin Stats",

        # Settings menu buttons
        "btn_language": "Language",
        "btn_profile": "My Profile",
        "btn_bot_info": "Bot Info",
        "btn_set_gif": "Set Welcome GIF",
        "btn_set_dev": "Set Dev Info",

        # Language menu buttons
        "btn_lang_en": "English",
        "btn_lang_ar": "Arabic",
        "btn_lang_ru": "Russian",

        # Content operations
        "send_content": "Send me the content (photo, video, document, audio, voice, text, sticker, animation — anything):",
        "set_delete_time": "Set the auto-delete time in seconds (e.g. 20).\nSend 0 to disable auto-delete:",
        "content_added": "Content added successfully.\n\nYour temporary link:\n<code>{link}</code>\n\nDelete after: {time}s",
        "content_added_no_delete": "Content added successfully.\n\nYour temporary link:\n<code>{link}</code>\n\nAuto-delete: Disabled",
        "invalid_time": "Please enter a valid number (0 or more).",
        "no_links": "You have no links yet.",
        "link_deleted": "Link deleted successfully.",
        "link_not_found": "Link not found or already expired.",
        "content_sent": "Here is your requested content:",
        "content_auto_delete": "This content will be deleted in {time} seconds.",
        "content_expired": "This link has expired or the content has been deleted.",
        "select_link_delete": "Choose the content link to delete:",
        "confirm_delete": "Are you sure you want to delete this link?\n\nContent: {type}\nViews: {views}",
        "select_content_viewers": "Choose content to view its viewers:",
        "no_viewers": "No one has viewed this content yet.",
        "viewer_line": "⌯ Viewer: <a href=\"tg://user?id={vid}\">{name}</a>\n⌯ View Count: {count}",
        "link_item": "{num}. Type: {type} | Views: {views} | Expires: {expire}\nLink: <code>{link}</code>",
        "my_links_text": "Your Links:\n\n{items}",
        "choose_link_viewers": "Choose content to see its viewers:",

        # Admin operations
        "send_admin_id": "Send me the user ID or username of the new admin:",
        "user_not_found": "User not found. The user must have started the bot first.",
        "already_admin": "This user is already an admin.",
        "admin_added": "Admin added successfully.",
        "no_admins": "There are no admins currently.",
        "admins_list": "Current Admins:",
        "admin_removed": "Admin removed successfully. User is now a regular member.",
        "choose_admin_edit": "Choose the admin to edit permissions:",
        "permissions_updated": "Permissions updated successfully.",
        "owner_cannot_remove": "You cannot remove the owner.",
        "self_cannot_remove": "You cannot remove yourself.",
        "need_manage_perm": "You do not have permission to manage admins.",
        "admin_stats_text": "Admin Statistics:\n\nTotal Admins: {count}\nActive Today: {active}",

        # Permissions labels
        "perm_add_content": "Add Content",
        "perm_delete_content": "Delete Content",
        "perm_view_stats": "View Statistics",
        "perm_manage_admins": "Manage Admins",
        "perm_change_language": "Change Language",
        "perm_view_viewers": "View Viewers",

        # Settings
        "language_changed": "Language changed to English.",
        "current_language": "Current language: English",
        "bot_info_text": "Bot Information:\n\nVersion: 1.0.0\nOwner ID: {owner_id}\nTotal Users: {users}\nTotal Content: {content}\nTotal Views: {views}",
        "send_gif": "Send me the GIF to use as welcome animation:",
        "gif_saved": "Welcome GIF saved successfully.",
        "send_dev_name": "Send the developer name:",
        "send_dev_id": "Send the developer Telegram ID:",
        "send_dev_username": "Send the developer username (without @):",
        "send_dev_photo": "Send the developer photo (or /skip to keep current):",
        "dev_info_saved": "Developer info saved successfully.",
        "profile_text": "Your Profile:\n\nName: {name}\nID: <code>{id}</code>\nUsername: @{username}\nRole: {role}\nJoined: {joined}",

        # Developer
        "dev_info_text": "• Dev Info\n\n- Name : <a href=\"tg://user?id={id}\">{name}</a>\n- ID : <code>{id}</code>\n- Username : @{username}\n- Rank : DeV",

        # Stats
        "all_content_text": "All Content:\n\nTotal Links: {total}\nActive Links: {active}\nExpired Links: {expired}",
        "popular_text": "Most Viewed Content:\n\n{items}",
        "recent_views_text": "Recent Views:\n\n{items}",
        "total_views_text": "Total Statistics:\n\nTotal Views: {views}\nUnique Viewers: {unique}\nContent Added: {content}",
        "no_content": "No content found.",

        # Roles
        "role_owner": "Owner",
        "role_admin": "Admin",
        "role_member": "Member",
        "yes": "Yes",
        "no": "No",
        "cancel_btn": "CNCL",

        # ─── DEV TOOLS — 10 main buttons ─────────────────────────────────────────
        "btn_dev_users": "Users Panel",
        "btn_dev_broadcast": "Broadcast",
        "btn_dev_system": "System Info",
        "btn_dev_db": "DB Control",
        "btn_dev_links": "All Links",
        "btn_dev_announce": "Announcements",
        "btn_dev_config": "Bot Config",
        "btn_dev_maintenance": "Maintenance",
        "btn_dev_export": "Export Data",
        "btn_dev_tools": "Dev Tools",

        # Users Panel sub-buttons
        "btn_dev_all_users": "View All Users",
        "btn_dev_search_user": "Search User",
        "btn_dev_ban_user": "Ban User",
        "btn_dev_unban_user": "Unban User",
        "btn_dev_user_count": "User Count",
        "btn_dev_last_active": "Last Active",

        # Broadcast sub-buttons
        "btn_dev_send_all": "Send to All",
        "btn_dev_send_admins": "Send to Admins",
        "btn_dev_send_users_only": "Send to Users",
        "btn_dev_schedule": "Schedule Message",
        "btn_dev_view_sent": "View Sent",

        # System sub-buttons
        "btn_dev_uptime": "Bot Uptime",
        "btn_dev_memory": "Memory Usage",
        "btn_dev_db_size": "DB Size",
        "btn_dev_active_now": "Active Now",
        "btn_dev_errors": "Error Log",

        # DB Control sub-buttons
        "btn_dev_db_stats": "DB Stats",
        "btn_dev_clear_views": "Clear Views",
        "btn_dev_clear_states": "Clear States",
        "btn_dev_clear_expired": "Clear Expired",
        "btn_dev_reset_db": "Full Reset",

        # All Links sub-buttons
        "btn_dev_view_all_links": "View All Links",
        "btn_dev_active_links": "Active Links",
        "btn_dev_expired_links": "Expired Links",
        "btn_dev_delete_expired": "Delete Expired",
        "btn_dev_links_by_user": "Links by User",

        # Announcements sub-buttons
        "btn_dev_new_announce": "New Announcement",
        "btn_dev_send_announce": "Send Announcement",
        "btn_dev_view_announce": "View Sent",
        "btn_dev_delete_last_ann": "Delete Last",
        "btn_dev_clear_announce": "Clear All",

        # Bot Config sub-buttons
        "btn_dev_view_config": "View Config",
        "btn_dev_bot_commands": "Bot Commands",
        "btn_dev_set_bot_name": "Set Bot Name",
        "btn_dev_restart": "Restart Bot",
        "btn_dev_toggle_maint": "Toggle Maintenance",

        # Maintenance sub-buttons
        "btn_dev_enable_maint": "Enable Maintenance",
        "btn_dev_disable_maint": "Disable Maintenance",
        "btn_dev_maint_msg": "Set Message",
        "btn_dev_maint_status": "Status",
        "btn_dev_kick_sessions": "Kick Sessions",

        # Export sub-buttons
        "btn_dev_export_users": "Export Users",
        "btn_dev_export_content": "Export Content",
        "btn_dev_export_views": "Export Views",
        "btn_dev_export_admins": "Export Admins",
        "btn_dev_full_export": "Full Export",

        # Dev Tools sub-buttons
        "btn_dev_api_status": "API Status",
        "btn_dev_test_msg": "Test Message",
        "btn_dev_clear_cache": "Clear Cache",
        "btn_dev_update_cmds": "Update Commands",
        "btn_dev_view_errors": "View Errors",

        # Dev responses
        "dev_users_menu": "Users Panel - Choose an option:",
        "dev_broadcast_menu": "Broadcast - Choose an option:",
        "dev_system_menu": "System Info - Choose an option:",
        "dev_db_menu": "DB Control - Choose an option:",
        "dev_links_menu": "All Links - Choose an option:",
        "dev_announce_menu": "Announcements - Choose an option:",
        "dev_config_menu": "Bot Config - Choose an option:",
        "dev_maintenance_menu": "Maintenance - Choose an option:",
        "dev_export_menu": "Export Data - Choose an option:",
        "dev_tools_menu": "Dev Tools - Choose an option:",

        "dev_user_count": "Total registered users: {count}",
        "dev_all_users": "All Users ({count} total):\n\n{users}",
        "dev_user_item": "{num}. <a href=\"tg://user?id={id}\">{name}</a> | @{username} | Role: {role}",
        "dev_search_prompt": "Send the user ID or username to search:",
        "dev_user_not_found": "User not found.",
        "dev_user_found": "User Found:\n\nName: <a href=\"tg://user?id={id}\">{name}</a>\nID: <code>{id}</code>\nUsername: @{username}\nRole: {role}\nJoined: {joined}\nLast Seen: {last_seen}",
        "dev_ban_prompt": "Send the user ID to ban:",
        "dev_banned": "User <code>{id}</code> has been banned.",
        "dev_unban_prompt": "Send the user ID to unban:",
        "dev_unbanned": "User <code>{id}</code> has been unbanned.",
        "dev_last_active": "Last Active Users:\n\n{users}",
        "dev_broadcast_prompt": "Send the message to broadcast:",
        "dev_broadcast_done": "Broadcast complete. Sent to {count} users.",
        "dev_broadcast_admins_done": "Broadcast sent to {count} admins.",
        "dev_broadcast_users_done": "Broadcast sent to {count} regular users.",
        "dev_schedule_prompt": "Send: <seconds> <message> (e.g. 60 Hello everyone!)",
        "dev_scheduled": "Message scheduled for {time} seconds.",
        "dev_no_sent": "No sent broadcasts found.",
        "dev_uptime": "Bot Uptime: {uptime}",
        "dev_memory": "Memory Usage: {memory}",
        "dev_db_size": "Database Size: {size}",
        "dev_active_now": "Active users in last 10 min: {count}",
        "dev_db_stats": "Database Statistics:\n\nUsers: {users}\nContent: {content}\nViews: {views}\nAdmins: {admins}\nStates: {states}",
        "dev_views_cleared": "All content views have been cleared.",
        "dev_states_cleared": "All user states have been cleared.",
        "dev_expired_cleared": "All expired content has been removed.",
        "dev_reset_confirm": "Are you sure? This will delete ALL bot data. Reply YES to confirm.",
        "dev_reset_done": "Database has been fully reset.",
        "dev_all_links": "All Links:\n\nTotal: {total}\nActive: {active}\nExpired: {expired}",
        "dev_active_links_list": "Active Links ({count}):\n\n{items}",
        "dev_expired_links_list": "Expired Links ({count}):\n\n{items}",
        "dev_expired_deleted": "Deleted {count} expired links.",
        "dev_announce_prompt": "Send the announcement text:",
        "dev_announce_sent": "Announcement sent to {count} users.",
        "dev_no_announcements": "No announcements found.",
        "dev_ann_deleted": "Last announcement deleted.",
        "dev_ann_cleared": "All announcements cleared.",
        "dev_config_text": "Bot Configuration:\n\nToken: {token}\nOwner ID: {owner}\nDev ID: {dev_id}\nDB Path: {db}\nChannel: {channel}\nMaintenance: {maint}",
        "dev_bot_commands_text": "Bot Commands:\n\n/start — Start the bot\n/help — Help message",
        "dev_set_name_prompt": "Bot name cannot be changed via API. Change it at @BotFather.",
        "dev_restarting": "Restarting bot... Please re-run main.py.",
        "dev_maint_enabled": "Maintenance mode enabled. Only the developer can use the bot.",
        "dev_maint_disabled": "Maintenance mode disabled. Bot is now accessible.",
        "dev_maint_msg_prompt": "Send the maintenance message to show users:",
        "dev_maint_msg_set": "Maintenance message updated.",
        "dev_maint_status": "Maintenance Mode: {status}\nMessage: {msg}",
        "dev_sessions_cleared": "All user sessions and states cleared.",
        "dev_export_done": "Export file ready.",
        "dev_no_data": "No data found to export.",
        "dev_api_status": "API Status: Connected\nTelegram API: OK\nBot Token: Valid\nDB Connection: OK",
        "dev_test_sent": "Test message sent successfully.",
        "dev_cache_cleared": "Bot cache cleared.",
        "dev_commands_updated": "Bot commands updated.",
        "dev_errors_text": "Recent errors logged: {count}\nCheck your terminal/log file for details.",
        "maintenance_msg": "Bot is under maintenance. Please try again later.",
        "user_banned_msg": "You have been banned from using this bot.",
        "item_added": "Item {count} added. Send more content or type <b>skip</b> to finish:",
        "no_items_yet": "Please send at least one item first before typing skip.",
        "multi_content_added": "Content added successfully ({count} items).\n\nYour temporary link:\n<code>{link}</code>\n\nDelete after: {time}s",
        "multi_content_added_no_delete": "Content added successfully ({count} items).\n\nYour temporary link:\n<code>{link}</code>\n\nAuto-delete: Disabled",
    },

    "ar": {
        "welcome_line1": "WELCOME TO 333 BOT",
        "welcome_line2": "STAY UPDATED WITH OUR CHANNEL.",
        "welcome_line3": "TEAM 333",
        "no_access": "ليس لديك صلاحية لاستخدام هذا البوت.",
        "choose_option": "اختر خياراً:",
        "back": "رجوع",
        "cancel": "الغاء",
        "cancelled": "تم الالغاء.",
        "error": "حدث خطأ. حاول مجدداً.",
        "not_authorized": "غير مصرح لك بالقيام بهذا الاجراء.",

        "btn_content": "المحتوى",
        "btn_stats": "الاحصاءات",
        "btn_admin": "لوحة الادمن",
        "btn_settings": "الاعدادات",
        "btn_developer": "المطور",

        "btn_add_content": "اضافة محتوى",
        "btn_my_links": "روابطي",
        "btn_view_viewers": "عرض المشاهدين",
        "btn_delete_link": "حذف رابط",
        "btn_link_settings": "اعدادات الروابط",

        "btn_all_content": "كل المحتوى",
        "btn_popular": "الاكثر مشاهدة",
        "btn_recent_views": "المشاهدات الاخيرة",
        "btn_total_views": "اجمالي المشاهدات",
        "btn_export": "تصدير الاحصاءات",

        "btn_view_admins": "عرض الادمنية",
        "btn_add_admin": "اضافة ادمن",
        "btn_remove_admin": "ازالة ادمن",
        "btn_edit_permissions": "تعديل الصلاحيات",
        "btn_admin_stats": "احصاءات الادمنية",

        "btn_language": "اللغة",
        "btn_profile": "ملفي",
        "btn_bot_info": "معلومات البوت",
        "btn_set_gif": "تعيين GIF الترحيب",
        "btn_set_dev": "معلومات المطور",

        "btn_lang_en": "الانجليزية",
        "btn_lang_ar": "العربية",
        "btn_lang_ru": "الروسية",

        "send_content": "ارسل لي المحتوى (صورة، فيديو، مستند، صوت، نص، ملصق، أي شيء):",
        "set_delete_time": "حدد مدة الحذف التلقائي بالثواني (مثال: 20).\nارسل 0 لتعطيل الحذف التلقائي:",
        "content_added": "تمت اضافة المحتوى بنجاح.\n\nرابطك المؤقت:\n<code>{link}</code>\n\nالحذف بعد: {time} ثانية",
        "content_added_no_delete": "تمت اضافة المحتوى بنجاح.\n\nرابطك المؤقت:\n<code>{link}</code>\n\nالحذف التلقائي: معطل",
        "invalid_time": "الرجاء ادخال رقم صحيح (0 او اكثر).",
        "no_links": "ليس لديك روابط بعد.",
        "link_deleted": "تم حذف الرابط بنجاح.",
        "link_not_found": "الرابط غير موجود او انتهت صلاحيته.",
        "content_sent": "هذا المحتوى الخاص بك:",
        "content_auto_delete": "سيتم حذف هذا المحتوى خلال {time} ثانية.",
        "content_expired": "انتهت صلاحية هذا الرابط او تم حذف المحتوى.",
        "select_link_delete": "اختر رابط المحتوى للحذف:",
        "confirm_delete": "هل انت متاكد من حذف هذا الرابط؟\n\nالنوع: {type}\nالمشاهدات: {views}",
        "select_content_viewers": "اختر المحتوى لعرض مشاهديه:",
        "no_viewers": "لم يشاهد احد هذا المحتوى بعد.",
        "viewer_line": "⌯ المشاهد: <a href=\"tg://user?id={vid}\">{name}</a>\n⌯ مرات تكرار المشاهدة: {count}",
        "link_item": "{num}. النوع: {type} | المشاهدات: {views} | ينتهي: {expire}\nالرابط: <code>{link}</code>",
        "my_links_text": "روابطك:\n\n{items}",
        "choose_link_viewers": "اختر المحتوى لعرض مشاهديه:",

        "send_admin_id": "ارسل لي معرف المستخدم او اسم المستخدم للادمن الجديد:",
        "user_not_found": "المستخدم غير موجود. يجب ان يكون قد بدأ البوت اولاً.",
        "already_admin": "هذا المستخدم ادمن بالفعل.",
        "admin_added": "تمت اضافة الادمن بنجاح.",
        "no_admins": "لا يوجد ادمنية حالياً.",
        "admins_list": "الادمنية الحاليون:",
        "admin_removed": "تمت ازالة الادمن بنجاح. المستخدم الآن عضو عادي.",
        "choose_admin_edit": "اختر الادمن لتعديل صلاحياته:",
        "permissions_updated": "تم تحديث الصلاحيات بنجاح.",
        "owner_cannot_remove": "لا يمكنك ازالة المالك.",
        "self_cannot_remove": "لا يمكنك ازالة نفسك.",
        "need_manage_perm": "ليس لديك صلاحية ادارة الادمنية.",
        "admin_stats_text": "احصاءات الادمنية:\n\nاجمالي الادمنية: {count}\nنشط اليوم: {active}",

        "perm_add_content": "اضافة محتوى",
        "perm_delete_content": "حذف محتوى",
        "perm_view_stats": "عرض الاحصاءات",
        "perm_manage_admins": "ادارة الادمنية",
        "perm_change_language": "تغيير اللغة",
        "perm_view_viewers": "عرض المشاهدين",

        "language_changed": "تم تغيير اللغة الى العربية.",
        "current_language": "اللغة الحالية: العربية",
        "bot_info_text": "معلومات البوت:\n\nالاصدار: 1.0.0\nمعرف المالك: {owner_id}\nاجمالي المستخدمين: {users}\nاجمالي المحتوى: {content}\nاجمالي المشاهدات: {views}",
        "send_gif": "ارسل لي GIF لاستخدامه كترحيب:",
        "gif_saved": "تم حفظ GIF الترحيب بنجاح.",
        "send_dev_name": "ارسل اسم المطور:",
        "send_dev_id": "ارسل معرف تيليغرام المطور:",
        "send_dev_username": "ارسل اسم مستخدم المطور (بدون @):",
        "send_dev_photo": "ارسل صورة المطور (او /skip للابقاء على الحالية):",
        "dev_info_saved": "تم حفظ معلومات المطور بنجاح.",
        "profile_text": "ملفك الشخصي:\n\nالاسم: {name}\nالمعرف: <code>{id}</code>\nاسم المستخدم: @{username}\nالرتبة: {role}\nتاريخ الانضمام: {joined}",

        "dev_info_text": "• Dev Info\n\n- Name : <a href=\"tg://user?id={id}\">{name}</a>\n- ID : <code>{id}</code>\n- Username : @{username}\n- Rank : DeV",

        "all_content_text": "كل المحتوى:\n\nاجمالي الروابط: {total}\nالروابط النشطة: {active}\nالروابط المنتهية: {expired}",
        "popular_text": "المحتوى الاكثر مشاهدة:\n\n{items}",
        "recent_views_text": "المشاهدات الاخيرة:\n\n{items}",
        "total_views_text": "الاحصاءات الكاملة:\n\nاجمالي المشاهدات: {views}\nالمشاهدون الفريدون: {unique}\nالمحتوى المضاف: {content}",
        "no_content": "لا يوجد محتوى.",

        "role_owner": "المالك",
        "role_admin": "ادمن",
        "role_member": "عضو",
        "yes": "نعم",
        "no": "لا",
        "cancel_btn": "CNCL",

        # DEV TOOLS — 10 main buttons
        "btn_dev_users": "لوحة المستخدمين",
        "btn_dev_broadcast": "الارسال الجماعي",
        "btn_dev_system": "معلومات النظام",
        "btn_dev_db": "التحكم بالبيانات",
        "btn_dev_links": "كل الروابط",
        "btn_dev_announce": "الاعلانات",
        "btn_dev_config": "ضبط البوت",
        "btn_dev_maintenance": "وضع الصيانة",
        "btn_dev_export": "تصدير البيانات",
        "btn_dev_tools": "ادوات المطور",

        # Users Panel
        "btn_dev_all_users": "عرض الكل",
        "btn_dev_search_user": "بحث عن مستخدم",
        "btn_dev_ban_user": "حظر مستخدم",
        "btn_dev_unban_user": "رفع الحظر",
        "btn_dev_user_count": "عدد المستخدمين",
        "btn_dev_last_active": "آخر نشاط",

        # Broadcast
        "btn_dev_send_all": "ارسال للجميع",
        "btn_dev_send_admins": "ارسال للادمنية",
        "btn_dev_send_users_only": "ارسال للمستخدمين",
        "btn_dev_schedule": "جدولة رسالة",
        "btn_dev_view_sent": "عرض المرسلة",

        # System
        "btn_dev_uptime": "وقت التشغيل",
        "btn_dev_memory": "استخدام الذاكرة",
        "btn_dev_db_size": "حجم قاعدة البيانات",
        "btn_dev_active_now": "نشط الآن",
        "btn_dev_errors": "سجل الاخطاء",

        # DB Control
        "btn_dev_db_stats": "احصاءات البيانات",
        "btn_dev_clear_views": "مسح المشاهدات",
        "btn_dev_clear_states": "مسح الحالات",
        "btn_dev_clear_expired": "مسح المنتهية",
        "btn_dev_reset_db": "اعادة ضبط كامل",

        # All Links
        "btn_dev_view_all_links": "عرض كل الروابط",
        "btn_dev_active_links": "الروابط النشطة",
        "btn_dev_expired_links": "الروابط المنتهية",
        "btn_dev_delete_expired": "حذف المنتهية",
        "btn_dev_links_by_user": "الروابط حسب المستخدم",

        # Announcements
        "btn_dev_new_announce": "اعلان جديد",
        "btn_dev_send_announce": "ارسال اعلان",
        "btn_dev_view_announce": "عرض المرسلة",
        "btn_dev_delete_last_ann": "حذف الاخير",
        "btn_dev_clear_announce": "مسح الكل",

        # Bot Config
        "btn_dev_view_config": "عرض الاعدادات",
        "btn_dev_bot_commands": "اوامر البوت",
        "btn_dev_set_bot_name": "اسم البوت",
        "btn_dev_restart": "اعادة تشغيل",
        "btn_dev_toggle_maint": "تبديل الصيانة",

        # Maintenance
        "btn_dev_enable_maint": "تفعيل الصيانة",
        "btn_dev_disable_maint": "تعطيل الصيانة",
        "btn_dev_maint_msg": "تعيين الرسالة",
        "btn_dev_maint_status": "الحالة",
        "btn_dev_kick_sessions": "طرد الجلسات",

        # Export
        "btn_dev_export_users": "تصدير المستخدمين",
        "btn_dev_export_content": "تصدير المحتوى",
        "btn_dev_export_views": "تصدير المشاهدات",
        "btn_dev_export_admins": "تصدير الادمنية",
        "btn_dev_full_export": "تصدير كامل",

        # Dev Tools
        "btn_dev_api_status": "حالة API",
        "btn_dev_test_msg": "رسالة اختبار",
        "btn_dev_clear_cache": "مسح الكاش",
        "btn_dev_update_cmds": "تحديث الاوامر",
        "btn_dev_view_errors": "عرض الاخطاء",

        # Dev responses
        "dev_users_menu": "لوحة المستخدمين - اختر:",
        "dev_broadcast_menu": "الارسال الجماعي - اختر:",
        "dev_system_menu": "معلومات النظام - اختر:",
        "dev_db_menu": "التحكم بالبيانات - اختر:",
        "dev_links_menu": "كل الروابط - اختر:",
        "dev_announce_menu": "الاعلانات - اختر:",
        "dev_config_menu": "ضبط البوت - اختر:",
        "dev_maintenance_menu": "وضع الصيانة - اختر:",
        "dev_export_menu": "تصدير البيانات - اختر:",
        "dev_tools_menu": "ادوات المطور - اختر:",

        "dev_user_count": "اجمالي المستخدمين المسجلين: {count}",
        "dev_all_users": "كل المستخدمين ({count} اجمالي):\n\n{users}",
        "dev_user_item": "{num}. <a href=\"tg://user?id={id}\">{name}</a> | @{username} | الرتبة: {role}",
        "dev_search_prompt": "ارسل معرف المستخدم او اسمه للبحث:",
        "dev_user_not_found": "المستخدم غير موجود.",
        "dev_user_found": "تم ايجاد المستخدم:\n\nالاسم: <a href=\"tg://user?id={id}\">{name}</a>\nالمعرف: <code>{id}</code>\nاسم المستخدم: @{username}\nالرتبة: {role}\nتاريخ الانضمام: {joined}\nآخر ظهور: {last_seen}",
        "dev_ban_prompt": "ارسل معرف المستخدم للحظر:",
        "dev_banned": "تم حظر المستخدم <code>{id}</code>.",
        "dev_unban_prompt": "ارسل معرف المستخدم لرفع الحظر:",
        "dev_unbanned": "تم رفع الحظر عن المستخدم <code>{id}</code>.",
        "dev_last_active": "آخر المستخدمين النشطين:\n\n{users}",
        "dev_broadcast_prompt": "ارسل الرسالة للبث:",
        "dev_broadcast_done": "اكتمل البث. تم الارسال لـ {count} مستخدم.",
        "dev_broadcast_admins_done": "تم الارسال لـ {count} ادمن.",
        "dev_broadcast_users_done": "تم الارسال لـ {count} مستخدم عادي.",
        "dev_schedule_prompt": "ارسل: <ثواني> <رسالة> (مثال: 60 مرحبا)",
        "dev_scheduled": "تمت جدولة الرسالة بعد {time} ثانية.",
        "dev_no_sent": "لا يوجد بث مرسل.",
        "dev_uptime": "وقت تشغيل البوت: {uptime}",
        "dev_memory": "استخدام الذاكرة: {memory}",
        "dev_db_size": "حجم قاعدة البيانات: {size}",
        "dev_active_now": "المستخدمون النشطون في آخر 10 دقائق: {count}",
        "dev_db_stats": "احصاءات قاعدة البيانات:\n\nالمستخدمون: {users}\nالمحتوى: {content}\nالمشاهدات: {views}\nالادمنية: {admins}\nالحالات: {states}",
        "dev_views_cleared": "تم مسح جميع المشاهدات.",
        "dev_states_cleared": "تم مسح جميع حالات المستخدمين.",
        "dev_expired_cleared": "تم حذف المحتوى المنتهي الصلاحية.",
        "dev_reset_confirm": "هل انت متاكد؟ سيحذف هذا جميع بيانات البوت. ارسل نعم للتاكيد.",
        "dev_reset_done": "تمت اعادة ضبط قاعدة البيانات بالكامل.",
        "dev_all_links": "كل الروابط:\n\nالاجمالي: {total}\nالنشطة: {active}\nالمنتهية: {expired}",
        "dev_active_links_list": "الروابط النشطة ({count}):\n\n{items}",
        "dev_expired_links_list": "الروابط المنتهية ({count}):\n\n{items}",
        "dev_expired_deleted": "تم حذف {count} رابط منتهي الصلاحية.",
        "dev_announce_prompt": "ارسل نص الاعلان:",
        "dev_announce_sent": "تم ارسال الاعلان لـ {count} مستخدم.",
        "dev_no_announcements": "لا يوجد اعلانات.",
        "dev_ann_deleted": "تم حذف آخر اعلان.",
        "dev_ann_cleared": "تم مسح جميع الاعلانات.",
        "dev_config_text": "اعدادات البوت:\n\nالتوكن: {token}\nمعرف المالك: {owner}\nمعرف المطور: {dev_id}\nمسار البيانات: {db}\nالقناة: {channel}\nالصيانة: {maint}",
        "dev_bot_commands_text": "اوامر البوت:\n\n/start — بدء البوت\n/help — المساعدة",
        "dev_set_name_prompt": "لا يمكن تغيير اسم البوت عبر API. غيره من @BotFather.",
        "dev_restarting": "جاري اعادة التشغيل... يرجى تشغيل main.py مجدداً.",
        "dev_maint_enabled": "تم تفعيل وضع الصيانة. المطور فقط يستطيع استخدام البوت.",
        "dev_maint_disabled": "تم تعطيل وضع الصيانة. البوت متاح الآن.",
        "dev_maint_msg_prompt": "ارسل رسالة الصيانة التي ستظهر للمستخدمين:",
        "dev_maint_msg_set": "تم تحديث رسالة الصيانة.",
        "dev_maint_status": "وضع الصيانة: {status}\nالرسالة: {msg}",
        "dev_sessions_cleared": "تم مسح جميع جلسات وحالات المستخدمين.",
        "dev_export_done": "ملف التصدير جاهز.",
        "dev_no_data": "لا توجد بيانات للتصدير.",
        "dev_api_status": "حالة API: متصل\nتيليغرام API: جيد\nالتوكن: صالح\nقاعدة البيانات: جيد",
        "dev_test_sent": "تم ارسال رسالة الاختبار بنجاح.",
        "dev_cache_cleared": "تم مسح كاش البوت.",
        "dev_commands_updated": "تم تحديث اوامر البوت.",
        "dev_errors_text": "عدد الاخطاء المسجلة: {count}\nراجع الطرفية لمزيد من التفاصيل.",
        "maintenance_msg": "البوت تحت الصيانة. الرجاء المحاولة لاحقاً.",
        "user_banned_msg": "لقد تم حظرك من استخدام هذا البوت.",
        "item_added": "تمت اضافة العنصر {count}. ارسل المزيد او اكتب <b>skip</b> للانتهاء:",
        "no_items_yet": "الرجاء ارسال عنصر واحد على الاقل قبل الكتابة skip.",
        "multi_content_added": "تمت اضافة المحتوى بنجاح ({count} عناصر).\n\nرابطك المؤقت:\n<code>{link}</code>\n\nالحذف بعد: {time} ثانية",
        "multi_content_added_no_delete": "تمت اضافة المحتوى بنجاح ({count} عناصر).\n\nرابطك المؤقت:\n<code>{link}</code>\n\nالحذف التلقائي: معطل",
    },

    "ru": {
        "welcome_line1": "WELCOME TO 333 BOT",
        "welcome_line2": "STAY UPDATED WITH OUR CHANNEL.",
        "welcome_line3": "TEAM 333",
        "no_access": "У вас нет доступа к этому боту.",
        "choose_option": "Выберите опцию:",
        "back": "Назад",
        "cancel": "Отмена",
        "cancelled": "Действие отменено.",
        "error": "Произошла ошибка. Попробуйте снова.",
        "not_authorized": "У вас нет прав на выполнение этого действия.",

        "btn_content": "Контент",
        "btn_stats": "Статистика",
        "btn_admin": "Панель Админа",
        "btn_settings": "Настройки",
        "btn_developer": "Разработчик",

        "btn_add_content": "Добавить контент",
        "btn_my_links": "Мои ссылки",
        "btn_view_viewers": "Просмотр зрителей",
        "btn_delete_link": "Удалить ссылку",
        "btn_link_settings": "Настройки ссылок",

        "btn_all_content": "Весь контент",
        "btn_popular": "Популярный контент",
        "btn_recent_views": "Недавние просмотры",
        "btn_total_views": "Всего просмотров",
        "btn_export": "Экспорт статистики",

        "btn_view_admins": "Список администраторов",
        "btn_add_admin": "Добавить администратора",
        "btn_remove_admin": "Удалить администратора",
        "btn_edit_permissions": "Изменить права",
        "btn_admin_stats": "Статистика администраторов",

        "btn_language": "Язык",
        "btn_profile": "Мой профиль",
        "btn_bot_info": "Информация о боте",
        "btn_set_gif": "Установить GIF",
        "btn_set_dev": "Инфо разработчика",

        "btn_lang_en": "Английский",
        "btn_lang_ar": "Арабский",
        "btn_lang_ru": "Русский",

        "send_content": "Отправьте мне контент (фото, видео, документ, аудио, текст, стикер — всё что угодно):",
        "set_delete_time": "Установите время автоудаления в секундах (например: 20).\nОтправьте 0 чтобы отключить:",
        "content_added": "Контент успешно добавлен.\n\nВаша временная ссылка:\n<code>{link}</code>\n\nУдаление через: {time} сек",
        "content_added_no_delete": "Контент успешно добавлен.\n\nВаша временная ссылка:\n<code>{link}</code>\n\nАвтоудаление: Отключено",
        "invalid_time": "Пожалуйста, введите правильное число (0 или больше).",
        "no_links": "У вас пока нет ссылок.",
        "link_deleted": "Ссылка успешно удалена.",
        "link_not_found": "Ссылка не найдена или срок действия истёк.",
        "content_sent": "Вот ваш запрошенный контент:",
        "content_auto_delete": "Этот контент будет удалён через {time} секунд.",
        "content_expired": "Срок действия этой ссылки истёк или контент был удалён.",
        "select_link_delete": "Выберите ссылку для удаления:",
        "confirm_delete": "Вы уверены, что хотите удалить эту ссылку?\n\nТип: {type}\nПросмотры: {views}",
        "select_content_viewers": "Выберите контент для просмотра зрителей:",
        "no_viewers": "Никто ещё не просматривал этот контент.",
        "viewer_line": "⌯ Зритель: <a href=\"tg://user?id={vid}\">{name}</a>\n⌯ Количество просмотров: {count}",
        "link_item": "{num}. Тип: {type} | Просмотры: {views} | Истекает: {expire}\nСсылка: <code>{link}</code>",
        "my_links_text": "Ваши ссылки:\n\n{items}",
        "choose_link_viewers": "Выберите контент для просмотра зрителей:",

        "send_admin_id": "Отправьте мне ID пользователя или имя нового администратора:",
        "user_not_found": "Пользователь не найден. Пользователь должен сначала запустить бота.",
        "already_admin": "Этот пользователь уже является администратором.",
        "admin_added": "Администратор успешно добавлен.",
        "no_admins": "В данный момент нет администраторов.",
        "admins_list": "Текущие администраторы:",
        "admin_removed": "Администратор успешно удалён.",
        "choose_admin_edit": "Выберите администратора для редактирования прав:",
        "permissions_updated": "Права успешно обновлены.",
        "owner_cannot_remove": "Вы не можете удалить владельца.",
        "self_cannot_remove": "Вы не можете удалить себя.",
        "need_manage_perm": "У вас нет прав для управления администраторами.",
        "admin_stats_text": "Статистика администраторов:\n\nВсего: {count}\nАктивно сегодня: {active}",

        "perm_add_content": "Добавление контента",
        "perm_delete_content": "Удаление контента",
        "perm_view_stats": "Просмотр статистики",
        "perm_manage_admins": "Управление администраторами",
        "perm_change_language": "Изменение языка",
        "perm_view_viewers": "Просмотр зрителей",

        "language_changed": "Язык изменён на Русский.",
        "current_language": "Текущий язык: Русский",
        "bot_info_text": "Информация о боте:\n\nВерсия: 1.0.0\nID владельца: {owner_id}\nВсего пользователей: {users}\nВсего контента: {content}\nВсего просмотров: {views}",
        "send_gif": "Отправьте мне GIF для использования как приветствие:",
        "gif_saved": "GIF успешно сохранён.",
        "send_dev_name": "Отправьте имя разработчика:",
        "send_dev_id": "Отправьте Telegram ID разработчика:",
        "send_dev_username": "Отправьте имя пользователя разработчика (без @):",
        "send_dev_photo": "Отправьте фото разработчика (или /skip):",
        "dev_info_saved": "Информация о разработчике успешно сохранена.",
        "profile_text": "Ваш профиль:\n\nИмя: {name}\nID: <code>{id}</code>\nИмя пользователя: @{username}\nРоль: {role}\nДата присоединения: {joined}",

        "dev_info_text": "• Dev Info\n\n- Name : <a href=\"tg://user?id={id}\">{name}</a>\n- ID : <code>{id}</code>\n- Username : @{username}\n- Rank : DeV",

        "all_content_text": "Весь контент:\n\nВсего ссылок: {total}\nАктивные: {active}\nИстёкшие: {expired}",
        "popular_text": "Самый популярный контент:\n\n{items}",
        "recent_views_text": "Недавние просмотры:\n\n{items}",
        "total_views_text": "Общая статистика:\n\nВсего просмотров: {views}\nУникальных зрителей: {unique}\nДобавлено контента: {content}",
        "no_content": "Контент не найден.",

        "role_owner": "Владелец",
        "role_admin": "Администратор",
        "role_member": "Участник",
        "yes": "Да",
        "no": "Нет",
        "cancel_btn": "CNCL",

        # DEV TOOLS — 10 main buttons
        "btn_dev_users": "Панель Пользователей",
        "btn_dev_broadcast": "Рассылка",
        "btn_dev_system": "Системная Информация",
        "btn_dev_db": "Управление БД",
        "btn_dev_links": "Все Ссылки",
        "btn_dev_announce": "Объявления",
        "btn_dev_config": "Конфиг Бота",
        "btn_dev_maintenance": "Обслуживание",
        "btn_dev_export": "Экспорт Данных",
        "btn_dev_tools": "Инструменты",

        # Users Panel
        "btn_dev_all_users": "Все пользователи",
        "btn_dev_search_user": "Найти пользователя",
        "btn_dev_ban_user": "Заблокировать",
        "btn_dev_unban_user": "Разблокировать",
        "btn_dev_user_count": "Кол-во пользователей",
        "btn_dev_last_active": "Последняя активность",

        # Broadcast
        "btn_dev_send_all": "Отправить всем",
        "btn_dev_send_admins": "Отправить администраторам",
        "btn_dev_send_users_only": "Отправить пользователям",
        "btn_dev_schedule": "Запланировать",
        "btn_dev_view_sent": "Просмотреть отправленные",

        # System
        "btn_dev_uptime": "Время работы",
        "btn_dev_memory": "Использование памяти",
        "btn_dev_db_size": "Размер БД",
        "btn_dev_active_now": "Активные сейчас",
        "btn_dev_errors": "Журнал ошибок",

        # DB Control
        "btn_dev_db_stats": "Статистика БД",
        "btn_dev_clear_views": "Очистить просмотры",
        "btn_dev_clear_states": "Очистить состояния",
        "btn_dev_clear_expired": "Очистить истёкшие",
        "btn_dev_reset_db": "Полный сброс",

        # All Links
        "btn_dev_view_all_links": "Все ссылки",
        "btn_dev_active_links": "Активные ссылки",
        "btn_dev_expired_links": "Истёкшие ссылки",
        "btn_dev_delete_expired": "Удалить истёкшие",
        "btn_dev_links_by_user": "Ссылки по пользователю",

        # Announcements
        "btn_dev_new_announce": "Новое объявление",
        "btn_dev_send_announce": "Отправить объявление",
        "btn_dev_view_announce": "Просмотреть отправленные",
        "btn_dev_delete_last_ann": "Удалить последнее",
        "btn_dev_clear_announce": "Очистить все",

        # Bot Config
        "btn_dev_view_config": "Просмотреть конфиг",
        "btn_dev_bot_commands": "Команды бота",
        "btn_dev_set_bot_name": "Имя бота",
        "btn_dev_restart": "Перезапустить бота",
        "btn_dev_toggle_maint": "Переключить обслуживание",

        # Maintenance
        "btn_dev_enable_maint": "Включить обслуживание",
        "btn_dev_disable_maint": "Отключить обслуживание",
        "btn_dev_maint_msg": "Установить сообщение",
        "btn_dev_maint_status": "Статус",
        "btn_dev_kick_sessions": "Завершить сеансы",

        # Export
        "btn_dev_export_users": "Экспорт пользователей",
        "btn_dev_export_content": "Экспорт контента",
        "btn_dev_export_views": "Экспорт просмотров",
        "btn_dev_export_admins": "Экспорт администраторов",
        "btn_dev_full_export": "Полный экспорт",

        # Dev Tools
        "btn_dev_api_status": "Статус API",
        "btn_dev_test_msg": "Тестовое сообщение",
        "btn_dev_clear_cache": "Очистить кэш",
        "btn_dev_update_cmds": "Обновить команды",
        "btn_dev_view_errors": "Просмотреть ошибки",

        # Dev responses
        "dev_users_menu": "Панель пользователей - Выберите:",
        "dev_broadcast_menu": "Рассылка - Выберите:",
        "dev_system_menu": "Системная информация - Выберите:",
        "dev_db_menu": "Управление БД - Выберите:",
        "dev_links_menu": "Все ссылки - Выберите:",
        "dev_announce_menu": "Объявления - Выберите:",
        "dev_config_menu": "Конфиг бота - Выберите:",
        "dev_maintenance_menu": "Обслуживание - Выберите:",
        "dev_export_menu": "Экспорт данных - Выберите:",
        "dev_tools_menu": "Инструменты - Выберите:",

        "dev_user_count": "Всего зарегистрированных пользователей: {count}",
        "dev_all_users": "Все пользователи ({count} всего):\n\n{users}",
        "dev_user_item": "{num}. <a href=\"tg://user?id={id}\">{name}</a> | @{username} | Роль: {role}",
        "dev_search_prompt": "Отправьте ID пользователя или имя для поиска:",
        "dev_user_not_found": "Пользователь не найден.",
        "dev_user_found": "Пользователь найден:\n\nИмя: <a href=\"tg://user?id={id}\">{name}</a>\nID: <code>{id}</code>\nИмя пользователя: @{username}\nРоль: {role}\nДата: {joined}\nПоследняя активность: {last_seen}",
        "dev_ban_prompt": "Отправьте ID пользователя для блокировки:",
        "dev_banned": "Пользователь <code>{id}</code> заблокирован.",
        "dev_unban_prompt": "Отправьте ID пользователя для разблокировки:",
        "dev_unbanned": "Пользователь <code>{id}</code> разблокирован.",
        "dev_last_active": "Последние активные пользователи:\n\n{users}",
        "dev_broadcast_prompt": "Отправьте сообщение для рассылки:",
        "dev_broadcast_done": "Рассылка завершена. Отправлено {count} пользователям.",
        "dev_broadcast_admins_done": "Отправлено {count} администраторам.",
        "dev_broadcast_users_done": "Отправлено {count} обычным пользователям.",
        "dev_schedule_prompt": "Отправьте: <секунды> <сообщение> (пример: 60 Привет всем!)",
        "dev_scheduled": "Сообщение запланировано через {time} секунд.",
        "dev_no_sent": "Нет отправленных рассылок.",
        "dev_uptime": "Время работы бота: {uptime}",
        "dev_memory": "Использование памяти: {memory}",
        "dev_db_size": "Размер базы данных: {size}",
        "dev_active_now": "Активных пользователей за последние 10 минут: {count}",
        "dev_db_stats": "Статистика базы данных:\n\nПользователи: {users}\nКонтент: {content}\nПросмотры: {views}\nАдминистраторы: {admins}\nСостояния: {states}",
        "dev_views_cleared": "Все просмотры контента удалены.",
        "dev_states_cleared": "Все состояния пользователей удалены.",
        "dev_expired_cleared": "Весь истёкший контент удалён.",
        "dev_reset_confirm": "Вы уверены? Это удалит ВСЕ данные бота. Отправьте ДА для подтверждения.",
        "dev_reset_done": "База данных полностью сброшена.",
        "dev_all_links": "Все ссылки:\n\nВсего: {total}\nАктивные: {active}\nИстёкшие: {expired}",
        "dev_active_links_list": "Активные ссылки ({count}):\n\n{items}",
        "dev_expired_links_list": "Истёкшие ссылки ({count}):\n\n{items}",
        "dev_expired_deleted": "Удалено {count} истёкших ссылок.",
        "dev_announce_prompt": "Отправьте текст объявления:",
        "dev_announce_sent": "Объявление отправлено {count} пользователям.",
        "dev_no_announcements": "Объявления не найдены.",
        "dev_ann_deleted": "Последнее объявление удалено.",
        "dev_ann_cleared": "Все объявления удалены.",
        "dev_config_text": "Конфигурация бота:\n\nТокен: {token}\nID владельца: {owner}\nID разработчика: {dev_id}\nПуть к БД: {db}\nКанал: {channel}\nОбслуживание: {maint}",
        "dev_bot_commands_text": "Команды бота:\n\n/start — Запустить бота\n/help — Помощь",
        "dev_set_name_prompt": "Имя бота нельзя изменить через API. Измените его у @BotFather.",
        "dev_restarting": "Перезапуск бота... Запустите main.py снова.",
        "dev_maint_enabled": "Режим обслуживания включён. Только разработчик может использовать бота.",
        "dev_maint_disabled": "Режим обслуживания отключён. Бот снова доступен.",
        "dev_maint_msg_prompt": "Отправьте сообщение обслуживания для отображения пользователям:",
        "dev_maint_msg_set": "Сообщение обслуживания обновлено.",
        "dev_maint_status": "Режим обслуживания: {status}\nСообщение: {msg}",
        "dev_sessions_cleared": "Все пользовательские сессии и состояния удалены.",
        "dev_export_done": "Файл экспорта готов.",
        "dev_no_data": "Данные для экспорта не найдены.",
        "dev_api_status": "Статус API: Подключен\nTelegram API: OK\nТокен: Действителен\nБД: OK",
        "dev_test_sent": "Тестовое сообщение успешно отправлено.",
        "dev_cache_cleared": "Кэш бота очищен.",
        "dev_commands_updated": "Команды бота обновлены.",
        "dev_errors_text": "Зарегистрировано ошибок: {count}\nСм. терминал для подробностей.",
        "maintenance_msg": "Бот находится на техническом обслуживании. Попробуйте позже.",
        "user_banned_msg": "Вы заблокированы и не можете использовать этого бота.",
        "item_added": "Элемент {count} добавлен. Отправьте ещё или напишите <b>skip</b> чтобы завершить:",
        "no_items_yet": "Пожалуйста, отправьте хотя бы один элемент перед написанием skip.",
        "multi_content_added": "Контент успешно добавлен ({count} элементов).\n\nВаша временная ссылка:\n<code>{link}</code>\n\nУдаление через: {time} сек",
        "multi_content_added_no_delete": "Контент успешно добавлен ({count} элементов).\n\nВаша временная ссылка:\n<code>{link}</code>\n\nАвтоудаление: Отключено",
    }
}


def get_text(key: str, lang: str = "en", **kwargs) -> str:
    lang_dict = TEXTS.get(lang, TEXTS["en"])
    text = lang_dict.get(key, TEXTS["en"].get(key, key))
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, ValueError):
            pass
    return text
